services:
  mongo-db:
    image: mongo:latest
    ports:
      - '8000:8000'
    volumes:
      - db:/data/db
      - configdb:/data/configdb
    command: mongod --port 8000

volumes:
  db:
  configdb:
