apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  labels:
    app: webdb
spec:
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb
        image: mrxmoon/webdb
        resources:
          limits:
            cpu: "0.5"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        env:
        - name: MONGO_URI
          value: mongodb://root:root@db/
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webdb
  labels:
    app: webdb
spec:
  ports:
  - port: 5000
    targetPort: 5000 
    protocol: TCP
  selector:
    app: webdb
    