apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-db-config
data:
  MONGODB_URI: "mongodb://root:example@mongodb-service.snajim.svc.cluster.local:27017/"
  MONGODB_PORT: "27017"

  env:
  - name: MONGO_URI
    value:  # MongoDB URL from environment
  - name: MONGO_DB_NAME
    value: "flask_app_db"  
  - name: MONGO_COLLECTION_NAME
    value: "requests" 
    